# Generated by Django 4.1 on 2024-10-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_code_result_alter_code_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="input_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
