# Generated by Django 4.1 on 2024-10-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_code_input_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="execution_time",
            field=models.FloatField(null=True),
        ),
    ]
