# Generated by Django 4.1 on 2024-10-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_code_execution_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="execution_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
